name: "Dustin's Action in Action"
description: 'Greets someone and always returns 42.'
branding:
  icon: 'alert-triangle'
  color: 'orange'
inputs:
  who:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer:
    description: 'The answer to everything: 42'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who }}
