name: Test Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Run my own continaer action
        id: my-action
        uses: ./
        with:
          who: '@wulfland'

      - name: Answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"

      - name: Test
        if: ${{ steps.my-action.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
